enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

#_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/seguranca-da-informacao
_url: http://www.devfuria.com.br/seguranca-da-informacao

secao: html-canvas

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
